### ISSUE TITLE
[Urgent] Randomized will give the same supplicant name more than 1x

### ISSUE THREAD

**Issue by castellanocj1** [djotaku/prophecypracticum_django#50] opened 2024-09-29 23:45 UTC
<img width="514" alt="image" src="https://github.com/user-attachments/assets/f56d88ad-05fd-4e8e-9f38-e5afec74907f">

In either list of prophet or supplicant, no name should show up more than 1x

**Comment by djotaku** [comment] 2024-10-01 00:54
duplicate of #46

**Closed by djotaku** 2024-10-01 00:54 UTC
Labels: duplicate
